name: Build EXE for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --noconsole app.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/app.exe
